// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yctmkrwvsyiocxgyddzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljdG1rcnd2c3lpb2N4Z3lkZHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NTI5MTUsImV4cCI6MjA1ODUyODkxNX0.tifIQiJUeJlxrefYC96kMGG9JOfkvpxKNeAFhSj967Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);